import Head from 'next/head'
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from 'react-icons/ai'
import Link from 'next/link'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { useState } from 'react'
import deved from '../public/cute.png'
import code from '../public/cute.png'
import design from '../public/cute.png'
import consulting from '../public/cute.png'
import Image from 'next/image'
import web1 from '../public/cute.png'
import web2 from '../public/desk.png'
import web4 from '../public/cute.png'
import web5 from '../public/cute.png'
import web6 from '../public/cute.png'
import me1 from '../public/me1.png'
import me2 from '../public/me2.jpg'
import me3 from '../public/me3.png'
import me4 from '../public/me4.png'

import Card from './header'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  const [isOpen, setIsOpen] = useState(false)

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Estrella&apos;s portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40"> */}
      <main className=" bg-white px-10 dark:bg-gray-900  min-h-screen md:px-28 lg:px-48 xl:px-60 2xl:px-7">
        {/* <section className="min-h-screen"> */}
        <section className="mb-24 sm:mb-16">
          <nav className="py-10 mb-4 flex justify-between  dark:text-white">
            <h1 className="font-semibold text-2xl">Estrella</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <nav className="flex justify-start sm:flex-col">
            <ul className="flex sm:justify-evenly">
              <li className="font-medium mr-8 sm:mr-0 transition ease-in-out hover:underline hover:duration-75">
                <a href="https://github.com/estrella-mooney" target="_blank">
                  Github
                </a>
              </li>
              <li className="font-medium mr-8 sm:mr-0 transition ease-in-out hover:underline hover:duration-75">
                <a href="https://github.com/estrella-mooney" target="_blank">
                  Email
                </a>
              </li>
              <li className="font-medium mr-8 sm:mr-0 transition ease-in-out hover:underline hover:duration-75">
                <a href="https://github.com/estrella-mooney" target="_blank">
                  LinkedIn
                </a>
              </li>
            </ul>
          </nav>
        </section>

        <section className="grid lg:grid-cols-2 gap-10 mb-36 sm:mb-16">
          <div className="w-96 sm:text-center sm:max-w-xs">
            <p className=" font-bold mb-3 text-green-800">Hi, my name is</p>
            <h1 className="mb-3 rainbow-text ">Estrella Mooney</h1>
            <div className=" dark:text-white">
              <p className="mb-3">
                I&apos;m a software developer based in New Zealand. I just
                finished a 17 week Full Stack Software Developer bootcam @ Dev
                Academy Aotearoa
              </p>
              <p className="mb-3">
                I&apos;m mad about the outdoors, and any free time I get you can
                catch me in the mountains.
              </p>
              <p className="mb-3">
                I&apos;m ready to dive into the world of development
              </p>
            </div>
          </div>
          <div className="flex justify-center">
            <Image
              alt="yes"
              src={me4}
              className="py-5 md:max-w-sm sm:max-w-xs"
              loading="lazy"
              width={400}
              height={500}
            ></Image>
          </div>
        </section>
        {/* </section> */}

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Started my journey as a
              <span className="text-teal-500"> software developer </span>
              at Dev Academy. And am now ready and{' '}
              <span className="text-teal-500">excited </span>
              to get workin!
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-10 sm:gap-5 mb-36">
            <div className=" bg-gray-400 flex-1 p-7 rounded-lg my-6 max-w-sm hover:shadow-lg transition ease-in-out hover:bg-gray-400 duration-200 hover:text-contrast-white  text-gray-800 dark:text-gray-200 ">
              <Image
                alt="yes"
                src={web2}
                width={400}
                height={215}
                decoding="async"
                className="mb-3 rounded-lg"
                loading="lazy"
              ></Image>
              <h1 className="text-lg font-semibold mb-5">WanderLust</h1>
              <p className="font-light mb-5">
                A app for this na dih this at this nhg skjsjk
              </p>
              <a href="https://github.com" title="GitHub">
                <svg
                  aria-hidden="true"
                  className="octicon octicon-mark-github"
                  height="24"
                  version="1.1"
                  viewBox="0 0 16 16"
                  width="24"
                >
                  <path
                    fillRule="evenodd"
                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"
                  ></path>
                </svg>
              </a>
            </div>
            <div className="flex-1 p-7 rounded-lg my-6 max-w-sm hover:shadow-lg transition ease-in-out hover:bg-accent-gold duration-200 hover:text-contrast-white  text-gray-800 dark:text-gray-200 ">
              <Image
                alt="yes"
                src={web2}
                width={400}
                height={215}
                decoding="async"
                className="mb-3 rounded-lg"
                loading="lazy"
              ></Image>
              <h1 className="text-lg font-semibold mb-5">Buddy</h1>
              <p className="font-light mb-5">
                A app for this na dih this at this nhg skjsjk
              </p>
              <a href="https://github.com" title="GitHub">
                <svg
                  aria-hidden="true"
                  className="octicon octicon-mark-github"
                  height="24"
                  version="1.1"
                  viewBox="0 0 16 16"
                  width="24"
                >
                  <path
                    fillRule="evenodd"
                    d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0 0 16 8c0-4.42-3.58-8-8-8z"
                  ></path>
                </svg>
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
